apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-credentials
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-kubernetes
  target:
    creationPolicy: Owner
  data:
    - secretKey: adminPassword
      remoteRef:
        key: "Grafana"
        property: password
