apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: "1.15.0"
      #version: "67.5.0"
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: external-dns
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
    # ignore:
    #   # Ignore "validated" annotation which is not inserted during install
    #   - paths: ["/metadata/annotations/prometheus-operator-validated"]
    #     target:
    #       kind: PrometheusRule
  values:
    sources:
      - ingress
    policy: sync
    provider:
      name: cloudflare
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: cloudflare-api-key
            key: apiKey
