apiVersion: v1
kind: Service
metadata:
  labels:
    app: overseerr
  name: overseerr-svc
  namespace: overseerr
spec:
  ports:
    - port: 5055
      protocol: TCP
      targetPort: 5055
  selector:
    app: overseerr
  type: LoadBalancer
