apiVersion: v1
kind: Service
metadata:
  labels:
    app: overseerr
  name: overseerr-svc
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5055
  selector:
    app: overseerr
  type: ClusterIP
