apiVersion: v1
kind: Service
metadata:
  labels:
    app: overseerr
  name: overseerr-svc
  namespace: overseerr
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: overseerr
  type: ClusterIP

