apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jackett-pvc
  namespace: jackett
  labels:
    app: jackett
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
