apiVersion: v1
kind: Service
metadata:
  labels:
    app: sonarr
  name: sonarr-svc
spec:
  ports:
    - port: 8989
      protocol: TCP
      targetPort: 8989
  selector:
    app: sonarr
  type: LoadBalancer
