apiVersion: v1
data:
    1password-credentials.json: ENC[AES256_GCM,data:SVwwq9yogtoUAdFDO9+aEODK9MIu6JfNf5Sp/FjpR+fw8CJNXlz/N5U7j0iSAfOe5KsqBbicL9FHwClsU2Wm1Uuw7FNYtyjSkndOhKkq3VJ7CsQPfg051zUhhMzkrIb2OqghQuFvHAZkKL1/+rDYCcD/CxAvGpYCzEm861dGLt0CXuBD30WX0+UQB8pXSa9L91RkCRTfqGNpflcEFYBF/F9JpYPfez99saWwdqKGqaKfpvgGqrFIJCAr0LhFUkR7cySzvSMQCZN/IpClN7SawmydmrUwNKned0LrIKNpYi3GJHsKSInTPn82lDwjE71Yp9Sca13+6nxKfmVzfuUqrDKWPTUEJ7hn0xpJl+c9zxXFb5lGUvKTzhzEoXpdxqojiszl5w6AP4mTQBG4NvkUYx6HOHB1pP5FxfVlMKVYiHIsDCnBLscEepUIbdBtRgtAJ0JyS9t/3gtukR9g6sGkQX/MukICviZGuA/Z4izOtkhJWjJ6LscXsLqaYrg4FRypB9e+swOZYq+CMyjrY3DXNOGdrtKCXVjFrx0ABcFjQu4O6/PTOr4VZyEKHJ1u1lZBKE55p9OX14nMeoY4aZMjyvCXVnQ/AvuQg0/wswsCan+OHCGjvFPOIUH9Xk8obA0v9LUH3onbC2fUdoJWUDQsnoal31SyHfa21nZI4QNa83w/CxtwNcM9zqFJ94pENYSuYENwPcAAGvfg53pQ2f8IAOe68f58UKEHYHGZkCHbX73rx04eXLxnrzrTWYPFHc949NFzjIl95VpRkTE/6ijkyKhSDlvaY5VsMPRAflG4xi3d8NpN1dqEuv6saFsVIJzakT5NW81ON+bLFjU6RgPw6Cr1uhUTui6euyKZ4L1AObgCNrvdlkzc5HPumyInUXDF0pjXV9zgtTg3oV21UysPR0nY4R5jXI4rnM0IS50eVgWVnhVxpXrVMRSnGp8RCqWb7DdJ6mwo1++YcTSk1+daj6HDj9cxpH89hLig5N9st/HbWIV6BqBZGerDpZUon0uuFM7/l1PoC8SAEaVjgt9Gt2BDBTPNrRUfva/vjFZhpMa22Y8wZAAtDQ98hjKk9eK1ay+csspbUadfQ7ZjMi/QhT3lQ7vHG7RzFmURAsEV1YxiYB+N2PzRDr9NXpbOWNuQUKmlao35a6kdSI7BaVLQsIyv88ywP7bfbDojTz8olffVexmYUAhZjSznzN5V3oGSr7MD3Qq6sga5RukOXzl6DHJcdp32qAwvP0JBMWHEED2ou3vlOsVOYAkWUZsh6JCLegZMfHp0ftqfLlJDkWLSvZ1qGUdTHLfmtrFHq2vSUdJxoTgeTZK7pNUUYb552MJ+wjC/3TAWPPiUjBNBFex0JxIp0Fma74DLmKgnC4CfiSOC+Yi2vBNzuhZ/MJfIMyThK1l1dD0hdHVcR6zy/NJiPNb2bp/naKiG3On59U/E6YJ7pvld5+GFbxPt2nK0wc0KxCtqD3jigIbWj0E053c1QbWffEiN8epPuW8yd7SHW+nl1AMNRHGv28SRdPbpMrjGXagrvfzlP9PKXHncoLgV9lrepXT3gRxj9yH5BGAkOz9MfOuN0Brld/UhMmd3e27B+17h5iYRt3Hdh/awU+Cs5KvhwY3/9DSRXCSPB6G2FUOCsiQOKRo6geh1hNAa3vL/n0bUJqEEJ0xxUc6qAO2RxTOCp/YH+OdlRimsY6aGVqZDhtUa2lt/+xoACEiZhLcLn1GB11uijUR19rX6I1mkKx8jp/r7AwNuWWJP0nGDm1qFaDwEhtEwfIUBtl4IMnNZSIsRkvqi4pFjUVtRiA33GBch1tlFlFLpuptM1K8//8GROgVYYi4nef5MSNvuBKE66xKjwVWz9lAR36Q9aWufSuS2vQQICtqHOz3i+0OAMdh5EbEru0uCYAset+TkBtlbY2ssEMjjoA7p3o4c,iv:G9H/GSkwouiGdFheZPIwwVVo1NcC7W4AFfH7CE2N28M=,tag:mZ7EizGv6JRF4zennz+3EA==,type:str]
kind: Secret
metadata:
    name: 1password-credentials
    namespace: secrets
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xxs0qv0zdeyxs493lzh8ay66ksafakkl5c6lg33r9jl037x7kcqsvflujf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2WVlnbXNXQXBmeVI0d3Yr
            NElJQ2gyR2JUM2NMcUZUZmp0SFdDSm5zMzI0Cm11dXR2NUVxNlViZ294YUVsMlc2
            VlZ5aFh6WHFUT1krdDZqZlNXQXJDL0UKLS0tIFhkOVJFaXpmbFQ3VjQwOW0rSCsw
            aHNONUYzVzR1a09uMExQZU9jUUF3ME0K6uHAHx9qQHSyJ5pozoi5aZE51tDHMQIM
            XctoNvVXId2V3POc/508qA5KpwcSxKnsiEgJOebivBC8rwQnX9S7ZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-09T18:05:56Z"
    mac: ENC[AES256_GCM,data:q874oSU7h69owVNUSHDwtlTtB9m7+lsp4vmP5E8vC2XM+2eNwPGpje7YnhrTQYde5Bpdv5Y5lxHjEBAJz4RZ6avtyiGP5QMa6Rd875V9c3Czrai8BgaTo59Y7a4loWgrsAM2uOx4QlXRmatsJ0JoFCgaIUgh/ep9bLYIzu8RZ/M=,iv:O4KnDiJnwPsfjzeFqgeCFk5Ww9ZGRape3fIw26wnRkg=,tag:6eERvdIs6caHdD02PEnKvA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
