apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: onepassword-kubernetes
spec:
  provider:
    onepassword:
      connectHost: https://onepassword-connect:8080
      vaults:
        kubernetes: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-connect-token
            key: token
            namespace: secrets
