apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: anilist-credentials
  namespace: secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-kubernetes
  target:
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: "Anilist Credentials"
        property: username
    - secretKey: credential
      remoteRef:
        key: "Anilist Credentials"
        property: credential
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: plex-credentials
  namespace: secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-kubernetes
  target:
    creationPolicy: Owner
  data:
    - secretKey: credential
      remoteRef:
        key: "Plex Credentials"
        property: credential
