apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: plex-claim
  namespace: secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-kubernetes
  target:
    creationPolicy: Owner
  data:
    - secretKey: claim
      remoteRef:
        key: "Plex Credentials"
        property: claim
