apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-secrets
  namespace: secrets
spec:
  interval: 24h
  url: https://charts.external-secrets.io
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 10m
  ref:
    tag: v0.13.0
  url: https://github.com/external-secrets/external-secrets
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: secrets
spec:
  interval: 30m
  chart:
    spec:
      chart: external-secrets
      version: "0.14.3"
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: secrets
      interval: 12h
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
