apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: onepassword
  namespace: secrets
spec:
  interval: 24h
  url: https://1password.github.io/connect-helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: onepassword
  namespace: secrets
spec:
  interval: 30m
  chart:
    spec:
      chart: 1password/connect
      version: "1.17.0"
      sourceRef:
        kind: HelmRepository
        name: onepassword
        namespace: secrets
      interval: 12h
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
  valuesFrom:
    - kind: Secret
      name: 1password-credentials
      valuesKey: credentials.json
      targetPath: connect.credentials
  values:
    connect: {}
