apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: onepassword
  namespace: secrets
spec:
  interval: 24h
  url: https://1password.github.io/connect-helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: onepassword
  namespace: secrets
spec:
  interval: 30m
  chart:
    spec:
      chart: connect
      version: "1.17.0"
      sourceRef:
        kind: HelmRepository
        name: onepassword
        namespace: secrets
      interval: 12h
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
  # values:
  #   connect:
  #     credentials: /home/opuser/.op/data/1password-credentials.json
  #   extraVolumeMounts:
  #     - name: credentials
  #       mountPath: /home/opuser/.op/data/1password-credentials.json
  #       subPath: 1password-credentials.json
  #       readOnly: true
  #   extraVolumes:
  #     - name: credentials
  #       secret:
  #         secretName: op-credentials
