apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-config-pvc
  labels:
    app: transmission
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
