apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: anilist-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-kubernetes
  target:
    creationPolicy: Owner
  data:
    - secretKey: ANI_USERNAME
      remoteRef:
        key: "Anilist Credentials"
        property: username
    - secretKey: ANI_TOKEN
      remoteRef:
        key: "Anilist Credentials"
        property: credential
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: plex-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-kubernetes
  target:
    creationPolicy: Owner
  data:
    - secretKey: PLEX_TOKEN
      remoteRef:
        key: "Plex Credentials"
        property: credential
