apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plexanisync-pvc
  namespace: plexanisync
  labels:
    app: plexanisync
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
