apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: secrets
spec:
  interval: 30m
  chart:
    spec:
      chart: external-secrets
      version: "0.14.3"
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: secrets
      interval: 12h
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
