apiVersion: apps/v1
kind: Deployment
metadata:
  name: plexautolanguages
  namespace: plexautolanguages
  labels:
    app: plexautolanguages
spec:
  selector:
    matchLabels:
      app: plexautolanguages
  replicas: 0
  template:
    metadata:
      labels:
        app: plexautolanguages
    spec:
      containers:
        - name: plexautolanguages
          image: remirigal/plex-auto-languages
          env:
            - name: TZ
              value: Europe/Paris
            - name: PLEX_URL
              value: plex-svc.plex.svc.cluster.local
            - name: PLEX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: plex-credentials
                  key: PLEX_TOKEN
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          configMap:
            name: plexautolanguages
