apiVersion: apps/v1
kind: Deployment
metadata:
  name: plexautolanguages
  namespace: plexautolanguages
  labels:
    app: plexautolanguages
spec:
  selector:
    matchLabels:
      app: plexautolanguages
  replicas: 1
  template:
    metadata:
      labels:
        app: plexautolanguages
    spec:
      containers:
        - name: plexautolanguages
          image: remirigal/plex-auto-languages
          env:
            - name: TZ
              value: Europe/Paris
          volumeMounts:
            - name: config
              mountPath: /app/config
      volumes:
        - name: config
          configMap:
            name: plexautolanguages
