apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: plex-credentials
  namespace: plex
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-kubernetes
  target:
    creationPolicy: Owner
  data:
    - secretKey: PLEX_TOKEN
      remoteRef:
        key: "Plex Credentials"
        property: credential
