apiVersion: v1
kind: Service
metadata:
  name: plex
spec:
  type: LoadBalancer
  ports:
    # - port: 32400
    #   targetPort: web
    #   name: web
    - port: 32400
      targetPort: 32400
      protocol: TCP
  selector:
    app: plex
